# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
 
name: weixintuisong
 
on: push
#   schedule:
#     - cron:  '0 0 * * *'
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    
    - name: weixintuisong

      run: weixintuisong.exe
    
